import { useEffect, useState } from 'react';
import { api } from './api';
import './workspace.css';

const navigation = {
  EMPLOYEE: [['overview', 'Overview'], ['requests', 'Purchase requests']],
  MANAGER: [['overview', 'Overview'], ['requests', 'My requests'], ['approvals', 'Approval queue']],
  PROCUREMENT: [['overview', 'Overview'], ['requests', 'My requests'], ['procurement', 'Procurement hub'], ['inventory', 'Product catalogue']],
  WAREHOUSE: [['overview', 'Overview'], ['warehouse', 'Warehouse']],
  ADMIN: [['overview', 'Overview'], ['admin', 'User administration']]
};
const roles = ['EMPLOYEE', 'MANAGER', 'PROCUREMENT', 'WAREHOUSE', 'ADMIN'];

function decodeToken(token) { try { return JSON.parse(atob(token.split('.')[1].replace(/-/g, '+').replace(/_/g, '/'))); } catch { return null; } }
function Status({ value }) { return <span className={`status ${value.toLowerCase()}`}>{value.replace('_', ' ')}</span>; }
function Empty({ title, text }) { return <div className="empty"><b>{title}</b><span>{text}</span></div>; }

export default function App() {
  const [token, setToken] = useState(localStorage.getItem('procureflow_token') || '');
  const [page, setPage] = useState('overview');
  const [requests, setRequests] = useState([]);
  const [notice, setNotice] = useState('');
  const user = decodeToken(token);
  const loadRequests = async () => { if (token) try { setRequests(await api('/purchase-requests/mine', { token })); } catch (e) { setNotice(e.message); } };
  useEffect(() => { loadRequests(); }, [token]);
  const signIn = accessToken => { localStorage.setItem('procureflow_token', accessToken); setToken(accessToken); setNotice('Welcome to ProcureFlow.'); };
  const signOut = () => { localStorage.removeItem('procureflow_token'); setToken(''); setRequests([]); };
  if (!token || !user) return <Auth onSignIn={signIn} />;
  const items = [...(navigation[user.role] || navigation.EMPLOYEE), ['notifications', 'Notifications']];
  const current = items.find(([id]) => id === page) || items[0];
  const go = target => { setPage(target); setNotice(''); };
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><span>PF</span><div><b>ProcureFlow</b><small>Operations suite</small></div></div><nav>{items.map(([id, label]) => <button className={page === id ? 'selected' : ''} key={id} onClick={() => go(id)}>{label}</button>)}</nav><div className="profile"><span>Signed in as</span><b>{user.role}</b><small>{user.email}</small></div></aside><main className="workspace"><header><div><span className="eyebrow">PROCUREMENT OPERATIONS</span><h1>{current[1]}</h1></div><button className="secondary" onClick={signOut}>Sign out</button></header>{notice && <div className="notice">{notice}</div>}{page === 'overview' && <Overview role={user.role} requests={requests} go={go} />}{page === 'requests' && <Requests token={token} requests={requests} reload={loadRequests} say={setNotice} />}{page === 'approvals' && <Approvals token={token} say={setNotice} />}{page === 'procurement' && <Procurement token={token} say={setNotice} />}{page === 'inventory' && <Inventory token={token} role={user.role} say={setNotice} />}{page === 'warehouse' && <Inventory token={token} role={user.role} say={setNotice} />}{page === 'admin' && <Admin token={token} say={setNotice} />}{page === 'notifications' && <Notifications token={token} />}</main></div>;
}

function Auth({ onSignIn }) {
  const [mode, setMode] = useState('login'); const [form, setForm] = useState({ fullName: '', email: '', password: '' }); const [error, setError] = useState('');
  const submit = async e => { e.preventDefault(); try { setError(''); const body = mode === 'login' ? { email: form.email, password: form.password } : form; onSignIn((await api(`/auth/${mode}`, { method: 'POST', body })).accessToken); } catch (err) { setError(err.message); } };
  return <main className="auth"><section><span className="eyebrow">B2B PROCUREMENT PLATFORM</span><h1>Every purchase.<br />One controlled flow.</h1><p>Requests, approvals, purchase orders, and stock operations—built for clear ownership.</p><div className="points">• Role-based access<br />• Auditable decisions<br />• Inventory visibility</div></section><form className="auth-card" onSubmit={submit}><span className="pf">PF</span><h2>{mode === 'login' ? 'Welcome back' : 'Create account'}</h2><p>{mode === 'login' ? 'Sign in to your operations workspace.' : 'Start with an employee workspace.'}</p>{mode === 'register' && <label>Full name<input required value={form.fullName} onChange={e => setForm({ ...form, fullName: e.target.value })} /></label>}<label>Email address<input required type="email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} /></label><label>Password<input required minLength="8" type="password" value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} /></label>{error && <p className="error">{error}</p>}<button>{mode === 'login' ? 'Sign in' : 'Create account'}</button><button type="button" className="link" onClick={() => setMode(mode === 'login' ? 'register' : 'login')}>{mode === 'login' ? 'New here? Create an account' : 'Already have an account? Sign in'}</button></form></main>;
}

function Overview({ role, requests, go }) {
  const pending = requests.filter(x => x.status === 'PENDING_APPROVAL').length; const approved = requests.filter(x => x.status === 'APPROVED').length;
  const action = role === 'MANAGER' ? ['approvals', 'Review approval queue'] : role === 'PROCUREMENT' ? ['procurement', 'Open procurement hub'] : role === 'WAREHOUSE' ? ['warehouse', 'Receive stock'] : ['requests', 'Create purchase request'];
  return <section className="stack"><section className="hero"><div><span className="eyebrow">WELCOME BACK</span><h2>Keep every purchase moving.</h2><p>Move confidently from request to receipt with clear ownership at every stage.</p><button onClick={() => go(action[0])}>{action[1]}</button></div><div className="role-circle">{role[0]}</div></section><section className="metrics"><Metric label="My requests" value={requests.length} hint="Across all statuses" /><Metric label="Awaiting decision" value={pending} hint="Pending approval" /><Metric label="Approved" value={approved} hint="Ready for procurement" /></section><section className="card"><SectionTitle title="Recent requests" text="Your latest procurement activity." action="View requests" onClick={() => go('requests')} />{requests.length ? <List rows={requests.slice(0, 5)} /> : <Empty title="No activity yet" text="Create a purchase request to begin your workflow." />}</section></section>;
}
function Metric({ label, value, hint }) { return <article className="metric"><span>{label}</span><strong>{value}</strong><small>{hint}</small></article>; }
function Notifications({ token }) {
  const [items, setItems] = useState([]); const [error, setError] = useState('');
  useEffect(() => { api('/notifications', { token }).then(setItems).catch(e => setError(e.message)); }, []);
  return <section className="stack"><div className="page-title"><div><span className="eyebrow">ACTIVITY CENTRE</span><h2>Notifications</h2><p>Updates generated by approvals, role changes, and purchase-order progress.</p></div></div>{error && <p className="error">{error}</p>}<section className="card">{items.length ? <div className="list">{items.map(x => <article key={x.id}><div><b>{x.title}</b><span>{x.message} · {new Date(x.createdAt).toLocaleString()}</span></div></article>)}</div> : <Empty title="No notifications" text="Workflow updates sent to you will appear here." />}</section></section>;
}
function SectionTitle({ title, text, action, onClick }) { return <div className="section-title"><div><h2>{title}</h2><p>{text}</p></div>{action && <button className="secondary" onClick={onClick}>{action}</button>}</div>; }
function List({ rows }) { return <div className="list">{rows.map(row => <article key={row.id}><div><b>{row.title || row.poNumber || row.name}</b><span>{row.currency ? `${row.currency} ${row.estimatedAmount || row.totalAmount}` : row.sku || row.email}</span></div>{row.status ? <Status value={row.status} /> : null}</article>)}</div>; }

function Requests({ token, requests, reload, say }) {
  const [form, setForm] = useState({ title: '', description: '', estimatedAmount: '', currency: 'INR' }); const [error, setError] = useState('');
  const submit = async e => { e.preventDefault(); try { setError(''); await api('/purchase-requests', { token, method: 'POST', body: { ...form, estimatedAmount: Number(form.estimatedAmount) } }); setForm({ title: '', description: '', estimatedAmount: '', currency: 'INR' }); await reload(); say('Purchase request submitted for approval.'); } catch (err) { setError(err.message); } };
  return <section className="two"><form className="card form" onSubmit={submit}><span className="eyebrow">NEW REQUEST</span><h2>Request a purchase</h2><p>Provide a clear business reason for your approver.</p><label>Request title<input required placeholder="e.g. Laptop for new employee" value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} /></label><label>Business reason<textarea placeholder="Why is this purchase needed?" value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} /></label><div className="fields"><label>Estimated amount<input required min="1" type="number" value={form.estimatedAmount} onChange={e => setForm({ ...form, estimatedAmount: e.target.value })} /></label><label>Currency<select value={form.currency} onChange={e => setForm({ ...form, currency: e.target.value })}><option>INR</option><option>USD</option></select></label></div>{error && <p className="error">{error}</p>}<button>Submit for approval</button></form><section className="card"><SectionTitle title="Request history" text="Track progress for every request." action="Refresh" onClick={reload} />{requests.length ? <List rows={requests} /> : <Empty title="No requests yet" text="Your submitted requests will appear here." />}</section></section>;
}

function Approvals({ token, say }) {
  const [items, setItems] = useState([]); const [notes, setNotes] = useState({}); const [error, setError] = useState('');
  const load = async () => { try { setItems(await api('/purchase-requests/pending', { token })); } catch (err) { setError(err.message); } }; useEffect(() => { load(); }, []);
  const decide = async (id, decision) => { try { await api(`/purchase-requests/${id}/decision`, { token, method: 'POST', body: { decision, comment: notes[id] || '' } }); say(`Request ${decision === 'APPROVE' ? 'approved' : 'rejected'}.`); load(); } catch (err) { setError(err.message); } };
  return <section className="stack"><div className="page-title"><div><span className="eyebrow">MANAGER WORKSPACE</span><h2>Approval queue</h2><p>Review requests and make a documented decision.</p></div><button className="secondary" onClick={load}>Refresh queue</button></div>{error && <p className="error">{error}</p>}{items.length ? items.map(item => <article className="card approval" key={item.id}><div className="approval-head"><div><h3>{item.title}</h3><p>{item.description || 'No business reason provided.'}</p></div><Status value={item.status} /></div><div className="meta"><span>Requested amount <b>{item.currency} {item.estimatedAmount}</b></span><span>Submitted {new Date(item.createdAt).toLocaleString()}</span></div><label>Decision note<textarea placeholder="Optional note for the requester" value={notes[item.id] || ''} onChange={e => setNotes({ ...notes, [item.id]: e.target.value })} /></label><div className="actions"><button className="danger" onClick={() => decide(item.id, 'REJECT')}>Reject</button><button onClick={() => decide(item.id, 'APPROVE')}>Approve request</button></div></article>) : <Empty title="Queue is clear" text="No requests are waiting for a manager decision." />}</section>;
}

function Procurement({ token, say }) {
  const [supplier, setSupplier] = useState({ name: '', email: '', taxIdentifier: '' }); const [order, setOrder] = useState({ purchaseRequestId: '', supplierId: '' }); const [suppliers, setSuppliers] = useState([]); const [approved, setApproved] = useState([]); const [orders, setOrders] = useState([]); const [error, setError] = useState('');
  const load = async () => { try { const [s, a, o] = await Promise.all([api('/suppliers', { token }), api('/purchase-requests/approved', { token }), api('/purchase-orders', { token })]); setSuppliers(s); setApproved(a); setOrders(o); } catch (err) { setError(err.message); } }; useEffect(() => { load(); }, []);
  const addSupplier = async e => { e.preventDefault(); try { const data = await api('/suppliers', { token, method: 'POST', body: supplier }); setSupplier({ name: '', email: '', taxIdentifier: '' }); setOrder({ ...order, supplierId: data.id }); say(`Supplier ${data.name} created.`); load(); } catch (err) { setError(err.message); } };
  const makeOrder = async e => { e.preventDefault(); try { const data = await api('/purchase-orders', { token, method: 'POST', body: order }); setOrder({ purchaseRequestId: '', supplierId: '' }); say(`Purchase order ${data.poNumber} created.`); load(); } catch (err) { setError(err.message); } };
  const advanceOrder = async (id, status) => { try { const data = await api(`/purchase-orders/${id}/status`, { token, method: 'PATCH', body: { status } }); say(`${data.poNumber} marked ${status.toLowerCase()}.`); load(); } catch (err) { setError(err.message); } };
  return <section className="stack"><div className="page-title"><div><span className="eyebrow">PROCUREMENT WORKSPACE</span><h2>Suppliers and purchase orders</h2><p>Convert approved business needs into controlled procurement records.</p></div><button className="secondary" onClick={load}>Refresh data</button></div>{error && <p className="error">{error}</p>}<div className="two"><form className="card form" onSubmit={addSupplier}><h2>Add supplier</h2><label>Supplier name<input required value={supplier.name} onChange={e => setSupplier({ ...supplier, name: e.target.value })} /></label><label>Contact email<input required type="email" value={supplier.email} onChange={e => setSupplier({ ...supplier, email: e.target.value })} /></label><label>Tax identifier<input required value={supplier.taxIdentifier} onChange={e => setSupplier({ ...supplier, taxIdentifier: e.target.value })} /></label><button>Add supplier</button></form><form className="card form" onSubmit={makeOrder}><h2>Create purchase order</h2><label>Approved request<select required value={order.purchaseRequestId} onChange={e => setOrder({ ...order, purchaseRequestId: e.target.value })}><option value="">Select approved request</option>{approved.map(x => <option key={x.id} value={x.id}>{x.title} — {x.currency} {x.estimatedAmount}</option>)}</select></label><label>Supplier<select required value={order.supplierId} onChange={e => setOrder({ ...order, supplierId: e.target.value })}><option value="">Select supplier</option>{suppliers.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label><button>Create purchase order</button></form></div><section className="card"><SectionTitle title="Purchase orders" text="Draft orders must be sent before they can be received." />{orders.length ? <div className="list">{orders.map(x => <article key={x.id}><div><b>{x.poNumber}</b><span>{x.currency} {x.totalAmount}</span></div><div className="actions"><Status value={x.status} />{x.status === 'DRAFT' && <button className="secondary" onClick={() => advanceOrder(x.id, 'SENT')}>Mark sent</button>}{x.status === 'SENT' && <button onClick={() => advanceOrder(x.id, 'RECEIVED')}>Mark received</button>}</div></article>)}</div> : <Empty title="No purchase orders yet" text="Approved requests will become purchase orders here." />}</section></section>;
}

function Inventory({ token, role, say }) {
  const [items, setItems] = useState([]); const [transactions, setTransactions] = useState([]); const [product, setProduct] = useState({ sku: '', name: '', reorderLevel: 0 }); const [receipt, setReceipt] = useState({ productId: '', quantity: '', referenceNote: '' }); const [error, setError] = useState(''); const warehouse = role === 'WAREHOUSE';
  const load = async () => { try { const [stock, ledger] = await Promise.all([api('/inventory', { token }), api('/inventory/transactions', { token })]); setItems(stock); setTransactions(ledger); } catch (err) { setError(err.message); } }; useEffect(() => { load(); }, []);
  const add = async e => { e.preventDefault(); try { const data = await api('/products', { token, method: 'POST', body: { ...product, reorderLevel: Number(product.reorderLevel) } }); setProduct({ sku: '', name: '', reorderLevel: 0 }); say(`${data.name} added to the catalogue.`); load(); } catch (err) { setError(err.message); } };
  const receive = async e => { e.preventDefault(); try { const data = await api('/inventory/receipts', { token, method: 'POST', body: { ...receipt, quantity: Number(receipt.quantity) } }); setReceipt({ productId: '', quantity: '', referenceNote: '' }); say(`Stock received. ${data.quantityOnHand} units now available.`); load(); } catch (err) { setError(err.message); } };
  return <section className="stack"><div className="page-title"><div><span className="eyebrow">{warehouse ? 'WAREHOUSE WORKSPACE' : 'PRODUCT CATALOGUE'}</span><h2>{warehouse ? 'Receive and track stock' : 'Products and stock levels'}</h2><p>{warehouse ? 'Record stock receipts to keep quantities accurate.' : 'Maintain the catalogue used by warehouse operations.'}</p></div><button className="secondary" onClick={load}>Refresh inventory</button></div>{error && <p className="error">{error}</p>}<div className="two"><section className="card"><SectionTitle title="Current stock" text="Live quantity on hand by product." />{items.length ? <div className="list">{items.map(x => <article key={x.productId}><div><b>{x.name}</b><span>{x.sku} · Reorder level {x.reorderLevel}</span></div><div className="quantity"><b>{x.quantityOnHand}</b><span className={x.lowStock ? 'low' : 'healthy'}>{x.lowStock ? 'Low stock' : 'In stock'}</span></div></article>)}</div> : <Empty title="Catalogue is empty" text="Add products before recording warehouse receipts." />}</section>{warehouse ? <form className="card form" onSubmit={receive}><h2>Receive stock</h2><label>Product<select required value={receipt.productId} onChange={e => setReceipt({ ...receipt, productId: e.target.value })}><option value="">Select product</option>{items.map(x => <option key={x.productId} value={x.productId}>{x.name} ({x.sku})</option>)}</select></label><label>Quantity received<input required min="1" type="number" value={receipt.quantity} onChange={e => setReceipt({ ...receipt, quantity: e.target.value })} /></label><label>Delivery reference<input placeholder="GRN or delivery note" value={receipt.referenceNote} onChange={e => setReceipt({ ...receipt, referenceNote: e.target.value })} /></label><button>Record stock receipt</button></form> : <form className="card form" onSubmit={add}><h2>Add catalogue product</h2><label>SKU<input required placeholder="e.g. LAP-14-PRO" value={product.sku} onChange={e => setProduct({ ...product, sku: e.target.value })} /></label><label>Product name<input required value={product.name} onChange={e => setProduct({ ...product, name: e.target.value })} /></label><label>Reorder level<input required min="0" type="number" value={product.reorderLevel} onChange={e => setProduct({ ...product, reorderLevel: e.target.value })} /></label><button>Add product</button></form>}</div><section className="card"><SectionTitle title="Inventory activity" text="The last 50 recorded movements provide an audit trail." />{transactions.length ? <div className="list">{transactions.map(x => <article key={x.id}><div><b>{x.productName}</b><span>{x.sku} · {x.referenceNote || 'No reference note'} · {new Date(x.createdAt).toLocaleString()}</span></div><div className="quantity"><b>+{x.quantityDelta}</b><span className="healthy">{x.transactionType}</span></div></article>)}</div> : <Empty title="No inventory activity" text="Recorded receipts and adjustments will appear here." />}</section></section>;
}

function Admin({ token, say }) {
  const [users, setUsers] = useState([]); const [error, setError] = useState(''); const load = async () => { try { setUsers(await api('/admin/users', { token })); } catch (err) { setError(err.message); } }; useEffect(() => { load(); }, []);
  const update = async (id, role) => { try { const data = await api(`/admin/users/${id}/role`, { token, method: 'PATCH', body: { role } }); say(`${data.fullName} is now ${data.role}.`); load(); } catch (err) { setError(err.message); } };
  return <section className="stack"><div className="page-title"><div><span className="eyebrow">ADMINISTRATION</span><h2>User access</h2><p>Assign responsibilities without direct database edits.</p></div><button className="secondary" onClick={load}>Refresh users</button></div>{error && <p className="error">{error}</p>}<section className="card"><SectionTitle title="Users" text={`${users.length} registered accounts`} />{users.length ? <div className="list users">{users.map(x => <article key={x.id}><div><b>{x.fullName}</b><span>{x.email}</span></div><select value={x.role} onChange={e => update(x.id, e.target.value)}>{roles.map(role => <option key={role}>{role}</option>)}</select></article>)}</div> : <Empty title="No users found" text="Registered users will appear here." />}</section></section>;
}
